### ISSUE TITLE
Dev branch

### ISSUE THREAD

**Issue by sberryman** [senecajs/seneca-amqp-transport#84]
When are you expecting to push the refactor?

**Comment by nfantone** [comment]
@sberryman You mean publish the next version to npm containing changes in `develop`? I didn't think it was worth it, since it doesn't add any new functionality (yet). So publishing a new artifact would make little sense.

All new features/PR should be made against latest `develop`, though. Why do ask? Is this preventing you from doing something or detrimental in some way?

**Comment by sberryman** [comment]
I just like the code in the `develop` branch quite a bit more and is easier to work with :) no rush though.

But yes, I did mean publish the `develop` branch to the npm.
